/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifpb.simba.criptografia.assimetrica;

import br.ifpb.simba.criptografia.assimetrica.encoder.AsymKeyGenerator;
import br.ifpb.simba.criptografia.assimetrica.encoder.EncoderEngine;
import br.ifpb.simba.criptografia.assimetrica.encoder.EncoderEngineImp;
import br.ifpb.simba.criptografia.assimetrica.encoder.NotPrimeNumberException;
import br.ifpb.simba.criptografia.assimetrica.encoder.PairPrimeGenerator;
import java.math.BigInteger;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Wensttay de Sousa Alencar <yattsnew@gmail.com>
 */
public class HomeScreen extends javax.swing.JFrame {

    private final PairPrimeGenerator generator;
    private final AsymKeyGenerator keyGenerator;
    private final EncoderEngine encoderEngine;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        generator = new PairPrimeGenerator();
        keyGenerator = new AsymKeyGenerator();
        encoderEngine = new EncoderEngineImp();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        inputTextP = new javax.swing.JTextField();
        inputTextQ = new javax.swing.JTextField();
        randomGeneratorButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        publicKeyField = new javax.swing.JTextField();
        privateKeyField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextMsg = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        encryptedField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        uncryptedField = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton1.setText("Gerar Chaves");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTextP.setText("Insira um Numero Primo");
        inputTextP.setToolTipText("Insira um Numero Primo");
        inputTextP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextPActionPerformed(evt);
            }
        });

        inputTextQ.setText("Insira outro Numero Primo");
        inputTextQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextQActionPerformed(evt);
            }
        });

        randomGeneratorButton.setText("Gerar P e Q");
        randomGeneratorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomGeneratorButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor de P:");

        jLabel2.setText("Valor de Q:");

        jLabel3.setText("Chave Publica:");

        jLabel4.setText("Chave Privada:");

        publicKeyField.setEditable(false);
        publicKeyField.setText("{e, n}");
        publicKeyField.setFocusable(false);

        privateKeyField.setEditable(false);
        privateKeyField.setText("{d, n}");
        privateKeyField.setFocusable(false);

        inputTextMsg.setColumns(20);
        inputTextMsg.setLineWrap(true);
        inputTextMsg.setRows(5);
        jScrollPane1.setViewportView(inputTextMsg);

        encryptedField.setEditable(false);
        encryptedField.setColumns(20);
        encryptedField.setLineWrap(true);
        encryptedField.setRows(5);
        encryptedField.setFocusable(false);
        jScrollPane2.setViewportView(encryptedField);

        jLabel5.setText("Mensagem a ser Enviada:");

        jLabel6.setText("Mensagem Criptografada:");

        uncryptedField.setEditable(false);
        uncryptedField.setColumns(20);
        uncryptedField.setLineWrap(true);
        uncryptedField.setRows(5);
        uncryptedField.setFocusable(false);
        jScrollPane3.setViewportView(uncryptedField);

        jLabel7.setText("Mensagem Descriptografada:");

        sendButton.setText("ENVIAR");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Gerar Chaves");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTextP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTextQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publicKeyField)
                            .addComponent(privateKeyField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomGeneratorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTextP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTextQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(randomGeneratorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publicKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(privateKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inputTextP.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomGeneratorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomGeneratorButtonActionPerformed
        generator.generateBigValues();
        inputTextP.setText(generator.getFirstNumber().toString());
        inputTextQ.setText(generator.getSecondNumber().toString());
    }//GEN-LAST:event_randomGeneratorButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pS = inputTextP.getText();
        String qS = inputTextQ.getText();
        try {
            BigInteger P = new BigInteger(pS);
            BigInteger Q = new BigInteger(qS);
            keyGenerator.generateAsymKeys(P, Q);

            privateKeyField.setText("{" + keyGenerator.getPrivateKey().getFistValue() + ", "
                    + keyGenerator.getPrivateKey().getSecondValue() + "}");
            publicKeyField.setText("{" + keyGenerator.getPublicKey().getFistValue() + ", "
                    + keyGenerator.getPublicKey().getSecondValue() + "}");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Valores de P e Q invalidos, tenten novamente com numeros inteiros primos!");
        } catch (NotPrimeNumberException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        if (inputTextP.getText().equals("") || inputTextP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Valor de P deve ser inserido!");
        } else if (inputTextQ.getText().equals("") || inputTextQ.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O Valor de P deve ser inserido!");
        } else {

            if (!keyGenerator.getPublicKey().isMissAValue()) {
                jButton2ActionPerformed(evt);
            }
            
            String msg = inputTextMsg.getText();

            BigInteger[] encodeMessage = (BigInteger[]) encoderEngine
                    .encodeMessage(msg, keyGenerator.getPublicKey());

            String decodeMessage = encoderEngine
                    .decodeMessage(encodeMessage, keyGenerator.getPrivateKey());

            StringBuilder encoded = new StringBuilder("");
            for (BigInteger bigInteger : encodeMessage) {
                encoded.append(new String(bigInteger.toByteArray()));
            }
            encryptedField.setText(encoded.toString());
            uncryptedField.setText(decodeMessage);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void inputTextPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextPActionPerformed
        inputTextP.setText("");
    }//GEN-LAST:event_inputTextPActionPerformed

    private void inputTextQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextQActionPerformed
        inputTextQ.setText("");
    }//GEN-LAST:event_inputTextQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea encryptedField;
    private javax.swing.JTextArea inputTextMsg;
    private javax.swing.JTextField inputTextP;
    private javax.swing.JTextField inputTextQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField privateKeyField;
    private javax.swing.JTextField publicKeyField;
    private javax.swing.JButton randomGeneratorButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea uncryptedField;
    // End of variables declaration//GEN-END:variables
}
